<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<c:set var="cp" value="${pageContext.request.contextPath}" />
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>질병 리스트</title>
<script>
function filterData() {
    var ageRange = document.getElementById("ageRange").value;
    var gender = document.getElementById("gender").value;
    var sickCd = document.getElementById("sickCd").value;
    window.location.href = "/disease/list?ageRange=" + ageRange + "&gender=" + gender + "&sickCd=" + sickCd;
}
</script>
</head>
<body>

 <label for="ageRange">연령대 선택:</label>
    <select id="ageRange">
        <option value="0_9">0세 ~ 9세</option>
        <option value="10_19">10세 ~ 19세</option>
        <option value="20_29">20세 ~ 29세</option>
        <option value="30_39">30세 ~ 39세</option>
        <option value="40_49">40세 ~ 49세</option>
        <option value="50_59">50세 ~ 59세</option>
        <option value="60_69">60세 ~ 69세</option>
        <option value="70_79">70세 ~ 79세</option>
        <option value="80_89">80세 ~ 89세</option>
    </select>
    
    <label for="gender">성별 선택:</label>
    <select id="gender">
        <option value="남">남성</option>
        <option value="여">여성</option>
    </select>
    
    <label for="sickCd">질병</label>
    <select id="sickCd">
    <option value="">질병 선택</option>
    <option value="A00">콜레라</option>
    <option value="A01">장티푸스 및 파라티푸스</option>
    <option value="A02">기타 살모넬라감염</option>
    <option value="A03">시겔라증</option>
    <option value="A04">기타 세균성 장감염</option>
    <option value="A05">달리 분류되지 않은 기타 세균성 음식매개중독</option>
    <option value="A06">아메바증</option>
    <option value="A07">기타 원충성 장질환</option>
    <option value="A08">바이러스성 및 기타 명시된 장감염</option>
    <option value="A09">감염성 및 상세불명 기원의 기타 위장염 및 결장염</option>
    <option value="A15">배양 유무에 관계 없이 가래 현미경 검사로 확인된 폐결핵</option>
    <option value="A16">세균학적으로나 조직학적으로 확인되지 않은 호흡기결핵</option>
    <option value="A17">신경계통의 결핵</option>
    <option value="A18">기타 기관의 결핵</option>
    <option value="A19">좁쌀결핵</option>
    <option value="A20">페스트</option>
    <option value="A21">야생토끼병</option>
    <option value="A22">탄저병</option>
    <option value="A23">브루셀라병</option>
    <option value="A24">마비저 및 유사비저</option>
    <option value="A25">쥐물음열</option>
    <option value="A26">유사단독</option>
    <option value="A27">렙토스피라병</option>
    <option value="A28">달리 분류되지 않은 기타 동물매개의 세균성 질환</option>
    <option value="A30">나병[한센병]</option>
    <option value="A31">기타 형태의 마이코박테리아에 의한 감염</option>
    <option value="A32">리스테리아증</option>
    <option value="A33">신생아파상풍</option>
    <option value="A34">산괴적 파상풍</option>
    <option value="A35">기타 파상풍</option>
    <option value="A36">디프테리아</option>
    <option value="A37">백일해</option>
    <option value="A38">성홍열</option>
    <option value="A39">수막알균감염</option>
    <option value="A40">연쇄알균패혈증</option>
    <option value="A41">기타 패혈증</option>
    <option value="A42">방션균증</option>
    <option value="A43">노카르디아증</option>
    <option value="A44">바르토넬라병</option>
    <option value="A46">단독(丹毒)</option>
    <option value="A48">달리 분류되지 않은 기타 세균성 질환</option>
    <option value="A49">상세불명 부위의 세균감염</option>
    <option value="A50">선천매독</option>
    <option value="A51">조기매독</option>
    <option value="A52">만기매독</option>
    <option value="A53">기타 및 상세불명의 매독</option>
    <option value="A54">임균감염</option>
    <option value="A55">클라미디아림프육아종(성병성)</option>
    <option value="A56">기타 성행위로 전파되는 클라미디아질환</option>
    <option value="A57">무른궤양</option>
    <option value="A58">사타구니육아종</option>
    <option value="A59">편모충증</option>
    <option value="A60">항문생식기의 헤르페스바이러스[단순헤르페스]감염</option>
    <option value="A63">달리 분류되지 않은 기타 주로 성행위로 전파되는 질환</option>
    <option value="A64">상세불명의 성매개질환</option>
    <option value="A66">요스</option>
    <option value="A67">핀타</option>
    <option value="A68">재귀열</option>
    <option value="A69">기타 스피로헤타감염</option>
    <option value="A70">클라미디아 시타시 감염</option>
    <option value="A71">트라코마</option>
    <option value="A74">클라미디아에 의한 기타 질환</option>
    <option value="A75">발진티푸스</option>
    <option value="A77">홍반열 (진드기매개 리케차병)</option>
    <option value="A78">큐열</option>
    <option value="A79">기타 리케차병</option>
    <option value="A80">급성 회색질척수염</option>
    <option value="A81">중추신경계통의 비정형 바이러스 감염</option>
    <option value="A82">광견병</option>
    <option value="A83">모기 매개 바이러스 뇌염</option>
    <option value="A84">진드기 매개 바이러스 뇌염</option>
    <option value="A85">달리 분류되지 않은 기타 바이러스 뇌염</option>
    <option value="A86">상세불명의 바이러스 뇌염</option>
    <option value="A87">바이러스 수막염</option>
    <option value="A88">달리 분류되지 않은 중추신경계통의 기타 바이러스 감염</option>
    <option value="A89">중추신경계통의 상세불명의 바이러스 감염</option>
    <option value="A92">기타 모기 매개 바이러스열</option>
    <option value="A93">달리 분류되지 않은 기타 절지 동물 매개 바이러스열</option>
    <option value="A94">상세불명의 절지 동물 매개 바이러스열</option>
    <option value="A95">황열</option>
    <option value="A96">아레나 바이러스 출혈열</option>
    <option value="A97">뎅기</option>
    <option value="A98">달리 분류되지 않은 기타 바이러스 출혈열</option>
    <option value="A99">상세불명의 바이러스 출혈열</option>
    
    <option value="B00">헤르페스 바이러스 [단순 헤르페스] 감염</option>
    <option value="B01">수두</option>
    <option value="B02">대상포진</option>
    <option value="B03">마마</option>
    <option value="B04">원숭이 두창</option>
    <option value="B05">홍역</option>
    <option value="B06">풍진</option>
    <option value="B07">바이러스 사마귀</option>
    <option value="B08">달리 분류되지 않은 피부 및 점막병변이 특징인 기타 바이러스 감염</option>
    <option value="B09">피부 및 점막병변이 특징인 상세불명의 바이러스 감염</option>
    <option value="B15">급성 A형간염</option>
    <option value="B16">급성 B형간염</option>
    <option value="B17">기타 급성 바이러스간염</option>
    <option value="B18">만성 바이러스간염</option>
    <option value="B19">상세불명의 바이러스간염</option>
    <option value="B20">감염성 및 기생충성 질환을 유발한 인체면역결핍바이러스병</option>
    <option value="B21">악성 신생물을 유발한 인체면역결핍바이러스병</option>
    <option value="B22">기타 명시된 질환을 유발한 인체면역결핍바이러스병</option>
    <option value="B23">기타병태를 유발한 인체면역결핍바이러스병</option>
    <option value="B24">상세불명의 인체면역결핍바이러스병</option>
    <option value="B25">거대세포바이러스병</option>
    <option value="B26">볼거리</option>
    <option value="B27">감염성 단핵구증</option>
    <option value="B30">바이러스결막염</option>
    <option value="B33">달리 분류되지 않은 기타 바이러스질환</option>
    <option value="B34">상세불명 부위의 바이러스감염</option>
    <option value="B35">백선증</option>
    <option value="B36">기타 표재성 진균증</option>
    <option value="B37">칸디다증</option>
    <option value="B38">콕시디오이데스진균증</option>
    <option value="B39">히스토플라스마증</option>
    <option value="B40">분아균증</option>
    <option value="B41">파라콕시디오이데스진균증</option>
    <option value="B42">스포로트릭스증</option>
    <option value="B43">색소진균증 및 피오진균농양</option>
    <option value="B44">아스페르길루스증</option>
    <option value="B45">크립토콕쿠스증</option>
    <option value="B46">접합진균증</option>
    <option value="B47">진균종</option>
    <option value="B48">달리 분류되지 않은 기타 진균증</option>
    <option value="B49">상세불명의 진균증</option>
    <option value="B50">열대열원충말라리아</option>
    <option value="B51">삼일열원충말라리아</option>
    <option value="B52">사일열원충말라리아</option>
    <option value="B53">기타 기생충학적으로 확인된 말라리아</option>
    <option value="B54">상세불명의 말라리아</option>
    <option value="B55">리슈만편모충증</option>
    <option value="B56">아프리카파동편모충증</option>
    <option value="B57">샤가스병</option>
    <option value="B58">톡소포자충증</option>
    <option value="B59">폐포자충증(J17.3*)</option>
    <option value="B60">달리 분류되지 않은 기타 원충질환</option>
    <option value="B64">상세불명의 원충병</option>
    <option value="B65">주혈흡충증</option>
    <option value="B66">기타 흡충감염</option>
    <option value="B67">포충증</option>
    <option value="B68">조충증</option>
    <option value="B69">낭미충증</option>
    <option value="B70">열두조충증 및 고충증</option>
    <option value="B71">기타 조충감염</option>
    <option value="B72">메디나충증</option>
    <option value="B73">회선사상충증</option>
    <option value="B74">사상충증</option>
    <option value="B75">선모충증</option>
    <option value="B76">구충병</option>
    <option value="B77">회충증</option>
    <option value="B78">분선충증</option>
    <option value="B79">편충증</option>
    <option value="B80">요충증</option>
    <option value="B81">달리 분류되지 않은 기타 장연충증</option>
    <option value="B82">상세불명의 장기생충증</option>
    <option value="B83">기타 연충증</option>
    <option value="B85">이감염증 및 사면발이증</option>
    <option value="B86">옴</option>
    <option value="B87">구더기증</option>
    <option value="B88">기타 감염</option>
    <option value="B89">상세불명의 기생충병</option>
    <option value="B90">결핵의 후유증</option>
    <option value="B91">회색질척수염의 후유증</option>
    <option value="B92">나병의 후유증</option>
    <option value="B94">기타 및 상세불명의 감염성 및 기생충성 질환의 후유증</option>
    <option value="B95">다른 장에서 분류된 질환의 원인으로서의 연쇄구균 및 포도구균</option>
    <option value="B96">다른 장에서 분류된 질환의 원인으로서의 기타 명시된 세균감염체</option>
    <option value="B97">다른 장에서 분류된 질환의 원인으로서의 바이러스감염체</option>
    <option value="B98">다른 장에서 분류된 질환의 원인으로서의 기타 명시된 감염체</option>
    <option value="B99">기타 및 상세불명의 감염성 질환</option>
    
     <option value="C00">입술의 악성 신생물</option>
    <option value="C01">혓바닥의 악성 신생물</option>
    <option value="C02">혀의 기타 및 상세불명 부분의 악성 신생물</option>
    <option value="C03">잇몸의 악성 신생물</option>
    <option value="C04">입바닥의 악성 신생물</option>
    <option value="C05">구개의 악성 신생물</option>
    <option value="C06">입의 기타 및 상세불명 부분의 악성 신생물</option>
    <option value="C07">귀밑샘의 악성 신생물</option>
    <option value="C08">기타 및 상세불명의 주침샘의 악성 신생물</option>
    <option value="C09">편도의 악성 신생물</option>
    <option value="C10">입인두의 악성 신생물</option>
    <option value="C11">비인두의 악성 신생물</option>
    <option value="C12">이상동(梨狀洞)의 악성 신생물</option>
    <option value="C13">하인두의 악성 신생물</option>
    <option value="C14">입술, 구강 및 인두내의 기타 및 부위불명의 악성 신생물</option>
    <option value="C15">식도의 악성 신생물</option>
    <option value="C16">위의 악성 신생물</option>
    <option value="C17">소장의 악성 신생물</option>
    <option value="C18">결장의 악성 신생물</option>
    <option value="C19">직장구불결장접합부의 악성 신생물</option>
    <option value="C20">직장의 악성 신생물</option>
    <option value="C21">항문 및 항문관의 악성 신생물</option>
    <option value="C22">간 및 간내 담관의 악성 신생물</option>
    <option value="C23">담낭의 악성 신생물</option>
    <option value="C24">담도의 기타 및 상세불명 부분의 악성 신생물</option>
    <option value="C25">췌장의 악성 신생물</option>
    <option value="C26">기타 및 부위불명 소화기관의 악성 신생물</option>
    <option value="C30">비강 및 중이의 악성 신생물</option>
    <option value="C31">부비동의 악성 신생물</option>
    <option value="C32">후두의 악성 신생물</option>
    <option value="C33">기관의 악성 신생물</option>
    <option value="C34">기관지 및 폐의 악성 신생물</option>
    <option value="C37">흉선의 악성 신생물</option>
    <option value="C38">심장, 종격 및 흉막의 악성 신생물</option>
    <option value="C39">기타 및 부위불명의 호흡기 및 흉곽내기관의 악성 신생물</option>
    <option value="C40">사지의 골 및 관절연골의 악성 신생물</option>
    <option value="C41">기타 및 상세불명 부위의 골 및 관절연골의 악성 신생물</option>
    <option value="C43">피부의 악성 흑색종</option>
    <option value="C44">기타 피부의 악성 신생물</option>
    <option value="C45">중피종</option>
    <option value="C46">카포시육종</option>
    <option value="C47">말초신경 및 자율신경계통의 악성 신생물</option>
    <option value="C48">후복막 및 복막의 악성 신생물</option>
    <option value="C49">기타 결합조직 및 연조직의 악성 신생물</option>
    <option value="C50">유방의 악성 신생물</option>
    <option value="C51">외음의 악성 신생물</option>
    <option value="C52">질의 악성 신생물</option>
    <option value="C53">자궁경부의 악성 신생물</option>
    <option value="C54">자궁체부의 악성 신생물</option>
    <option value="C55">자궁의 상세불명 부분의 악성 신생물</option>
    <option value="C56">난소의 악성 신생물</option>
    <option value="C57">기타 및 상세불명의 여성생식기관의 악성 신생물</option>
    <option value="C58">태반의 악성 신생물</option>
    <option value="C60">음경의 악성 신생물</option>
    <option value="C61">전립선의 악성 신생물</option>
    <option value="C62">고환의 악성 신생물</option>
    <option value="C63">기타 및 상세불명의 남성생식기관의 악성 신생물</option>
    <option value="C64">신우를 제외한 신장의 악성 신생물</option>
    <option value="C65">신우의 악성 신생물</option>
    <option value="C66">요관의 악성 신생물</option>
    <option value="C67">방광의 악성 신생물</option>
    <option value="C68">기타 및 상세불명의 비뇨기관의 악성 신생물</option>
    <option value="C69">눈 및 부속기의 악성 신생물</option>
    <option value="C70">수막의 악성 신생물</option>
    <option value="C71">뇌의 악성 신생물</option>
    <option value="C72">척수, 뇌신경 및 중추 신경계통의 기타 부분의 악성 신생물</option>
    <option value="C73">갑상선의 악성 신생물</option>
    <option value="C74">부신의 악성 신생물</option>
    <option value="C75">기타 내분비선 및 관련 구조물의 악성 신생물</option>
    <option value="C76">기타 및 부위불명의 악성 신생물</option>
    <option value="C77">림프절의 이차성 및 상세불명의 악성 신생물</option>
    <option value="C78">호흡 및 소화기관의 이차성 악성 신생물</option>
    <option value="C79">기타 및 상세불명 부위의 이차성 악성 신생물</option>
    <option value="C80">부위의 명시가 없는 악성 신생물</option>
    <option value="C81">호지킨 림프종</option>
    <option value="C82">소포성 림프종</option>
    <option value="C83">비소포성 림프종</option>
    <option value="C84">성숙 T/NK-세포 림프종</option>
    <option value="C85">기타 및 상세불명 유형의 비호지킨 림프종</option>
    <option value="C86">T/NK-세포 림프종의 기타 명시된 형태</option>
    <option value="C88">악성 면역증식성 질환</option>
    <option value="C90">다발골수종 및 악성 형질세포신생물</option>
    <option value="C91">림프성 백혈병</option>
    <option value="C92">골수성 백혈병</option>
    <option value="C93">단핵구성 백혈병</option>
    <option value="C94">명시된 세포형의 기타 백혈병</option>
    <option value="C95">상세불명 세포형의 백혈병</option>
    <option value="C96">림프, 조혈 및 관련 조직의 기타 및 상세불명의 악성 신생물</option>
    <option value="C97">독립된(원발성) 여러 부위의 악성 신생물</option>
    
     <option value="D37">구강 및 소화기관의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D38">중이, 호흡기관, 흉곽내기관의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D39">여성생식기관의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D40">남성생식기관의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D41">비뇨기관의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D42">수막의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D43">뇌 및 중추신경계통의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D44">내분비선의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D45">진성 적혈구증가증</option>
    <option value="D46">골수형성이상증후군</option>
    <option value="D47">림프, 조혈 및 관련 조직의 행동양식 불명 및 미상의 기타 신생물</option>
    <option value="D48">기타 및 상세불명 부위의 행동양식 불명 또는 미상의 신생물</option>
    <option value="D50">철결핍빈혈</option>
    <option value="D51">비타민B12결핍빈혈</option>
    <option value="D52">엽산결핍빈혈</option>
    <option value="D53">기타 영양성 빈혈</option>
    <option value="D55">효소장애에 의한 빈혈</option>
    <option value="D56">지중해빈혈</option>
    <option value="D57">낫적혈구장애</option>
    <option value="D58">기타 유전성 용혈성 빈혈</option>
    <option value="D59">후천성 용혈성 빈혈</option>
    <option value="D60">후천성 순수적혈구무형성[적모구감소]</option>
    <option value="D61">기타 무형성빈혈</option>
    <option value="D62">급성 출혈후 빈혈</option>
    <option value="D63">달리 분류된 만성 질환에서의 빈혈</option>
    <option value="D64">기타 빈혈</option>
    <option value="D65">파종성 혈관내응고[탈피브린증후군]</option>
    <option value="D66">유전성 제8인자결핍</option>
    <option value="D67">유전성 제9인자결핍</option>
    <option value="D68">기타 응고결함</option>
    <option value="D69">자반 및 기타 출혈성 병태</option>
    <option value="D70">무과립구증</option>
    <option value="D71">다형핵호중구의 기능장애</option>
    <option value="D72">백혈구의 기타 장애</option>
    <option value="D73">비장의 질환</option>
    <option value="D74">메트헤모글로빈혈증</option>
    <option value="D75">혈액 및 조혈기관의 기타 질환</option>
    <option value="D76">림프세망 및 세망조직구 조직의 참여를 동반한 기타 명시된 질환</option>
    <option value="D77">달리 분류된 질환에서 혈액 및 조혈기관의 기타 장애</option>
    <option value="D80">항체결손이 현저한 면역결핍</option>
    <option value="D81">복합면역결핍</option>
    <option value="D82">기타 주요 결손과 관련된 면역결핍</option>
    <option value="D83">공통 가변성 면역결핍</option>
    <option value="D84">기타 면역결핍</option>
    <option value="D86">사르코이드증</option>
    <option value="D89">달리 분류되지 않은 면역메커니즘을 침범한 기타 장애</option>
    
     <option value="E00">선천성 요오드결핍증후군</option>
    <option value="E01">요오드결핍과 관련된 갑상선장애 및 동류의 병태</option>
    <option value="E02">무증상 요오드결핍성 갑상선기능저하증</option>
    <option value="E03">기타 갑상선기능저하증</option>
    <option value="E04">기타 비독성 고이터</option>
    <option value="E05">갑상선독증[갑상선기능항진증]</option>
    <option value="E06">갑상선염</option>
    <option value="E07">갑상선의 기타 장애</option>
    <option value="E10">1형 당뇨병</option>
    <option value="E11">2형 당뇨병</option>
    <option value="E12">영양실조-관련 당뇨병</option>
    <option value="E13">기타 명시된 당뇨병</option>
    <option value="E14">상세불명의 당뇨병</option>
    <option value="E15">비당뇨병성 저혈당성 혼수</option>
    <option value="E16">췌장내분비의 기타 장애</option>
    <option value="E20">부갑상선기능저하증</option>
    <option value="E21">부갑상선기능항진증 및 부갑상선의 기타 장애</option>
    <option value="E22">뇌하수체의 기능항진</option>
    <option value="E23">뇌하수체의 기능저하 및 기타 장애</option>
    <option value="E24">쿠싱증후군</option>
    <option value="E25">부신생식기장애</option>
    <option value="E26">고알도스테론증</option>
    <option value="E27">부신의 기타 장애</option>
    <option value="E28">난소의 기능이상</option>
    <option value="E29">고환의 기능이상</option>
    <option value="E30">달리 분류되지 않은 사춘기의 장애</option>
    <option value="E31">다선성 기능이상</option>
    <option value="E32">흉선의 질환</option>
    <option value="E34">기타 내분비장애</option>
    <option value="E35">달리 분류된 질환에서의 내분비선장애</option>
    <option value="E40">콰시오르코르</option>
    <option value="E41">영양성 소모증</option>
    <option value="E42">소모성 쿠싱증</option>
    <option value="E43">상세불명의 중증 단백질</option>
    <option value="E44">중등도 및 경도의 단백질-에너지영양실조</option>
    <option value="E45">단백질-에너지영양실조로 인한 발육지연</option>
    <option value="E46">상세불명의 단백질-에너지영양실조</option>
    <option value="E50">비타민A결핍</option>
    <option value="E51">티아민결핍</option>
    <option value="E52">니아신결핍[펠라그라]</option>
    <option value="E53">기타 비타민B군의 결핍</option>
    <option value="E54">아스코르빈산결핍</option>
    <option value="E55">비타민D결핍</option>
    <option value="E56">기타 비타민결핍</option>
    <option value="E58">식사성 칼슘결핍</option>
    <option value="E59">식사성 셀레늄결핍</option>
    <option value="E60">식사성 아연결핍</option>
    <option value="E61">기타 영양소의 결핍</option>
    <option value="E63">기타 영양결핍</option>
    <option value="E64">영양실조 및 기타 영양결핍의 후유증</option>
    <option value="E65">국소적 지방과다</option>
    <option value="E66">비만</option>
    <option value="E67">기타 과영양</option>
    <option value="E68">과영양의 후유증</option>
    <option value="E70">방향족아미노산대사장애</option>
    <option value="E71">측쇄아미노산 및 지방산 대사장애</option>
    <option value="E72">아미노산대사의 기타 장애</option>
    <option value="E73">젖당불내성</option>
    <option value="E74">탄수화물대사의 기타 장애</option>
    <option value="E75">스핑고지질대사장애 및 기타 지질축적장애</option>
    <option value="E76">글리코사미노글라이칸대사장애</option>
    <option value="E77">당단백질대사장애</option>
    <option value="E78">지질단백질대사장애 및 기타 지질증</option>
    <option value="E79">퓨린 및 피리미딘의 대사장애</option>
    <option value="E80">포르피린 및 빌리루빈 대사장애</option>
    <option value="E83">무기질대사장애</option>
    <option value="E84">낭성 섬유증</option>
    <option value="E85">아밀로이드증</option>
    <option value="E86">용적고갈</option>
    <option value="E87">수분, 전해질 및 산-염기균형의 기타 장애</option>
    <option value="E88">기타 대사장애</option>
    <option value="E89">달리 분류되지 않은 처치후 내분비 및 대사 장애</option>
    <option value="E90">달리 분류된 질환에서의 영양 및 대사 장애</option>
    
    <option value="F00">알츠하이머병에서의 치매</option>
    <option value="F01">혈관성 치매</option>
    <option value="F02">달리 분류된 기타 질환에서의 치매</option>
    <option value="F03">상세불명의 치매</option>
    <option value="F04">알콜 및 기타 정신활성물질에 의해 유발된 것이 아닌 기질성 기억상실증후군</option>
    <option value="F05">알콜 및 기타 정신활성물질에 의하여 유발된 것이 아닌 섬망</option>
    <option value="F06">뇌손상, 뇌기능이상 및 신체질환에 의한 기타 정신장애</option>
    <option value="F07">뇌질환, 뇌손상 및 기능이상에 의한 인격 및 행동장애</option>
    <option value="F09">상세불명의 기질성 또는 증상성 정신장애</option>
    <option value="F10">알콜사용에 의한 정신 및 행동 장애</option>
    <option value="F11">아편유사제 사용에 의한 정신 및 행동 장애</option>
    <option value="F12">카나비노이드 사용에 의한 정신 및 행동 장애</option>
    <option value="F13">진정제 또는 수면제 사용에 의한 정신 및 행동 장애</option>
    <option value="F14">코카인 사용에 의한 정신 및 행동 장애</option>
    <option value="F15">카페인을 포함하는 기타 흥분제 사용에 의한 정신 및 행동 장애</option>
    <option value="F16">환각제 사용에 의한 정신 및 행동 장애</option>
    <option value="F17">담배흡연에 의한 정신 및 행동 장애</option>
    <option value="F18">휘발용제 사용에 의한 정신 및 행동 장애</option>
    <option value="F19">여러 약물 사용 및 기타 정신활성물질의 사용에 의한 정신 및 행동 장애</option>
    <option value="F20">조현병</option>
    <option value="F21">조현형장애</option>
    <option value="F22">지속성 망상장애</option>
    <option value="F23">급성 및 일과성 정신병장애</option>
    <option value="F24">유도망상장애</option>
    <option value="F25">조현정동장애</option>
    <option value="F28">기타 비기질성 정신병장애</option>
    <option value="F29">상세불명의 비기질성 정신병</option>
    <option value="F30">조증에피소드</option>
    <option value="F31">양극성 정동장애</option>
    <option value="F32">우울에피소드</option>
    <option value="F33">재발성 우울장애</option>
    <option value="F34">지속성 기분[정동]장애</option>
    <option value="F38">기타 기분[정동]장애</option>
    <option value="F39">상세불명의 기분[정동]장애</option>
    <option value="F40">공포성 불안장애</option>
    <option value="F41">기타 불안장애</option>
    <option value="F42">강박장애</option>
    <option value="F43">심한 스트레스에 대한 반응 및 적응장애</option>
    <option value="F44">해리[전환]장애</option>
    <option value="F45">신체형장애</option>
    <option value="F48">기타 신경성 장애</option>
    <option value="F50">식사장애</option>
    <option value="F51">비기질성 수면장애</option>
    <option value="F52">기질성 장애나 질병에 의하지 않은 성기능장애</option>
    <option value="F53">달리 분류되지 않은 산후기의 정신 및 행동 장애</option>
    <option value="F54">달리 분류된 장애나 질환에 연관된 심리적 요인 및 행동적 요인</option>
    <option value="F55">비의존성 물질의 남용</option>
    <option value="F59">생리적 장애 및 신체적 요인과 연관된 상세불명의 행동증후군</option>
    <option value="F60">특정 인격장애</option>
    <option value="F61">혼합형 및 기타 인격장애</option>
    <option value="F62">뇌 손상과 질병이 원인이 아닌 지속적인 인격변화</option>
    <option value="F63">습관 및 충동 장애</option>
    <option value="F64">성주체성장애</option>
    <option value="F65">성선호장애</option>
    <option value="F66">성적 발달과 지향에 관계된 심리적 장애 및 행동장애</option>
    <option value="F68">성인의 인격 및 행동의 기타 장애</option>
    <option value="F69">성인의 인격 및 행동의 상세불명의 장애</option>
    <option value="F70">경도 정신지체</option>
    <option value="F71">중등도 정신지체</option>
    <option value="F72">중증 정신지체</option>
    <option value="F73">최중증 정신지체</option>
    <option value="F78">기타 정신지체</option>
    <option value="F79">상세불명의 정신지체</option>
    <option value="F80">말하기와 언어의 특정 발달장애</option>
    <option value="F81">학습술기의 특정 발달장애</option>
    <option value="F82">운동기능의 특정 발달장애</option>
    <option value="F83">혼합형 특정 발달장애</option>
    <option value="F84">전반발달장애</option>
    <option value="F88">심리적 발달의 기타 장애</option>
    <option value="F89">심리적 발달의 상세불명의 장애</option>
    <option value="F90">운동과다장애</option>
    <option value="F91">행동장애</option>
    <option value="F92">행동 및 정서의 혼합 장애</option>
    <option value="F93">소아기에만 발병하는 정서장애</option>
    <option value="F94">소아기 및 청소년기에만 발병하는 사회적 기능수행장애</option>
    <option value="F95">틱장애</option>
    <option value="F98">소아기 및 청소년기에 주로 발병하는 기타 행동 및 정서장애</option>
    <option value="F99">정신장애 NOS</option>
    
    <option value="G00">달리 분류되지 않은 세균성 수막염</option>
    <option value="G01">달리 분류된 세균성 질환에서의 수막염</option>
    <option value="G02">달리 분류된 기타 감염성 및 기생충 질환에서의 수막염</option>
    <option value="G03">기타 및 상세불명의 원인에 의한 수막염</option>
    <option value="G04">뇌염, 척수염 및 뇌척수염</option>
    <option value="G05">달리 분류된 질환에서의 뇌염, 척수염 및 뇌척수염</option>
    <option value="G06">두개내 및 척추내 농양 및 육아종</option>
    <option value="G07">달리 분류된 질환에서의 두개내 및 척추내 농양 및 육아종</option>
    <option value="G08">두개내 및 척추내 정맥염 및 혈전정맥염</option>
    <option value="G09">중추신경계통의 염증성 질환의 후유증</option>
    <option value="G10">헌팅톤병</option>
    <option value="G11">유전성 운동실조</option>
    <option value="G12">척수성 근위축 및 관련 증후군</option>
    <option value="G13">달리 분류된 질환에서의 일차적으로 중추신경계통에 영향을 주는 계통성 위축</option>
    <option value="G14">소아마비후증후군</option>
    <option value="G20">파킨슨병</option>
    <option value="G21">이차성 파킨슨증</option>
    <option value="G22">달리 분류된 질환에서의 파킨슨증</option>
    <option value="G23">기저핵의 기타 퇴행성 질환</option>
    <option value="G24">근긴장이상</option>
    <option value="G25">기타 추체외로 및 운동 장애</option>
    <option value="G26">달리 분류된 질환에서의 추체외로 및 운동 장애</option>
    <option value="G30">알츠하이머병</option>
    <option value="G31">달리 분류되지 않은 신경계통의 기타 퇴행성 질환</option>
    <option value="G32">달리 분류된 질환에서의 신경계통의 기타 퇴행장애</option>
    <option value="G35">다발경화증</option>
    <option value="G36">기타 급성 파종성 탈수초</option>
    <option value="G37">중추신경계통의 기타 탈수초질환</option>
    <option value="G40">뇌전증</option>
    <option value="G41">뇌전증지속상태</option>
    <option value="G43">편두통</option>
    <option value="G44">기타 두통증후군</option>
    <option value="G45">일과성 뇌허혈발작 및 관련 증후군</option>
    <option value="G46">뇌혈관질환에서의 뇌의 혈관증후군(I60-I67†)</option>
    <option value="G47">수면장애</option>
    <option value="G50">삼차신경의 장애</option>
    <option value="G51">안면신경장애</option>
    <option value="G52">기타 뇌신경의 장애</option>
    <option value="G53">달리 분류된 질환에서의 뇌신경장애</option>
    <option value="G54">신경근 및 신경총 장애</option>
    <option value="G55">달리 분류된 질환에서의 신경근 및 신경총 압박</option>
    <option value="G56">팔의 단일신경병증</option>
    <option value="G57">다리의 단일신경병증</option>
    <option value="G58">기타 단일신경병증</option>
    <option value="G59">달리 분류된 질환에서의 단일신경병증</option>
    <option value="G60">유전성 및 특발성 신경병증</option>
    <option value="G61">염증성 다발신경병증</option>
    <option value="G62">기타 다발신경병증</option>
    <option value="G63">달리 분류된 질환에서의 다발신경병증</option>
    <option value="G64">말초신경계통의 기타 장애</option>
    <option value="G70">중증근무력증 및 기타 근신경장애</option>
    <option value="G71">근육의 원발성 장애</option>
    <option value="G72">기타 근병증</option>
    <option value="G73">달리 분류된 질환에서의 신경근접합부 및 근육의 장애</option>
    <option value="G80">뇌성마비</option>
    <option value="G81">편마비</option>
    <option value="G82">하반신마비 및 사지마비</option>
    <option value="G83">기타 마비증후군</option>
    <option value="G90">자율신경계통의 장애</option>
    <option value="G91">수두증</option>
    <option value="G92">독성뇌병증</option>
    <option value="G93">뇌의 기타 장애</option>
    <option value="G94">달리 분류된 질환에서의 뇌의 기타 장애</option>
    <option value="G95">척수의 기타 질환</option>
    <option value="G96">중추신경계통의 기타 장애</option>
    <option value="G97">달리 분류되지 않은 신경계통의 처치후 장애</option>
    <option value="G98">달리 분류되지 않은 신경계통의 기타 장애</option>
    <option value="G99">달리 분류된 질환에서의 신경계통의 기타 장애</option>
    
     <option value="H00">맥립종 및 콩다래끼</option>
    <option value="H01">눈꺼풀의 기타 염증</option>
    <option value="H02">눈꺼풀의 기타 장애</option>
    <option value="H03">달리 분류된 질환에서의 눈꺼풀의 장애</option>
    <option value="H04">눈물계통의 장애</option>
    <option value="H05">안와의 장애</option>
    <option value="H06">달리 분류된 질환에서의 눈물계통 및 안와의 장애</option>
    <option value="H10">결막염</option>
    <option value="H11">결막의 기타 장애</option>
    <option value="H13">달리 분류된 질환에서의 결막의 장애</option>
    <option value="H15">공막의 장애</option>
    <option value="H16">각막염</option>
    <option value="H17">각막 흉터 및 혼탁</option>
    <option value="H18">각막의 기타 장애</option>
    <option value="H19">달리 분류된 질환에서의 공막 및 각막의 장애</option>
    <option value="H20">홍채섬모체염</option>
    <option value="H21">홍채 및 섬모체의 기타 장애</option>
    <option value="H22">달리 분류된 질환에서의 홍채 및 섬모체의 장애</option>
    <option value="H25">노년백내장</option>
    <option value="H26">기타 백내장</option>
    <option value="H27">수정체의 기타 장애</option>
    <option value="H28">달리 분류된 질환에서의 백내장 및 수정체의 기타 장애</option>
    <option value="H30">맥락망막염증</option>
    <option value="H31">맥락막의 기타 장애</option>
    <option value="H32">달리 분류된 질환에서의 맥락망막장애</option>
    <option value="H33">망막박리 및 망막열공</option>
    <option value="H34">망막혈관폐쇄</option>
    <option value="H35">기타 망막장애</option>
    <option value="H36">달리 분류된 질환에서의 망막장애</option>
    <option value="H40">녹내장</option>
    <option value="H42">달리 분류된 질환에서의 녹내장</option>
    <option value="H43">유리체의 장애</option>
    <option value="H44">안구의 장애</option>
    <option value="H45">달리 분류된 질환에서의 유리체 및 안구의 장애</option>
    <option value="H46">시신경염</option>
    <option value="H47">시[제2]신경 및 시각경로의 기타 장애</option>
    <option value="H48">달리 분류된 질환에서의 시[제2]신경 및 시각경로의 장애</option>
    <option value="H49">마비성 사시</option>
    <option value="H50">기타 사시</option>
    <option value="H51">양안운동의 기타 장애</option>
    <option value="H52">굴절 및 조절의 장애</option>
    <option value="H53">시각장애</option>
    <option value="H54">실명을 포함한 시력장애(양안의 또는 단안의)</option>
    <option value="H55">안진 및 기타 불규칙적 눈운동</option>
    <option value="H57">눈 및 눈부속기의 기타 장애</option>
    <option value="H58">달리 분류된 질환에서의 눈 및 눈부속기의 기타 장애</option>
    <option value="H59">달리 분류되지 않은 눈 및 눈부속기의 처치후 장애</option>
    <option value="H60">외이염</option>
    <option value="H61">외이의 기타 장애</option>
    <option value="H62">달리 분류된 질환에서의 외이의 장애</option>
    <option value="H65">비화농성 중이염</option>
    <option value="H66">화농성 및 상세불명의 중이염</option>
    <option value="H67">달리 분류된 질환에서의 중이염</option>
    <option value="H68">귀인두관염 및 귀인두관 폐색</option>
    <option value="H69">귀인두관의 기타 장애</option>
    <option value="H70">유돌염 및 관련 병태</option>
    <option value="H71">중이의 진주종</option>
    <option value="H72">고막의 천공</option>
    <option value="H73">고막의 기타 장애</option>
    <option value="H74">중이 및 유돌의 기타 장애</option>
    <option value="H75">달리 분류된 질환에서의 중이 및 유돌의 기타 장애</option>
    <option value="H80">귀경화증</option>
    <option value="H81">전정기능의 장애</option>
    <option value="H82">달리 분류된 질환에서의 현기증후군</option>
    <option value="H83">내이의 기타 질환</option>
    <option value="H90">전음성 및 감각신경성 청력소실</option>
    <option value="H91">기타 청력소실</option>
    <option value="H92">귀통증 및 귀의 삼출액</option>
    <option value="H93">달리 분류되지 않은 귀의 기타 장애</option>
    <option value="H94">달리 분류된 질환에서의 귀의 기타 장애</option>
    <option value="H95">달리 분류되지 않은 귀 및 유돌의 처치후 장애</option>
    
    <option value="I00">심장침범에 대한 언급이 없는 류마티스열</option>
    <option value="I01">심장 침범이 있는 류마티스열</option>
    <option value="I02">류마티스무도병</option>
    <option value="I05">류마티스성 승모판질환</option>
    <option value="I06">류마티스성 대동맥판질환</option>
    <option value="I07">류마티스성 삼첨판질환</option>
    <option value="I08">다발판막질환</option>
    <option value="I09">기타 류마티스심장질환</option>
    <option value="I10">본태성(원발성) 고혈압</option>
    <option value="I11">고혈압성 심장병</option>
    <option value="I12">고혈압성 신장병</option>
    <option value="I13">고혈압성 심장 및 신장병</option>
    <option value="I15">이차성 고혈압</option>
    <option value="I20">협심증</option>
    <option value="I21">급성 심근경색증</option>
    <option value="I22">후속심근경색증</option>
    <option value="I23">급성 심근경색증 후 특정 현존 합병증</option>
    <option value="I24">기타 급성 허혈심장질환</option>
    <option value="I25">만성 허혈심장병</option>
    <option value="I26">폐색전증</option>
    <option value="I27">기타 폐성 심장질환</option>
    <option value="I28">폐혈관의 기타 질환</option>
    <option value="I30">급성 심장막염</option>
    <option value="I31">심장막의 기타 질환</option>
    <option value="I32">달리 분류된 질환에서의 심장막염</option>
    <option value="I33">급성 및 아급성 심내막염</option>
    <option value="I34">비류마티스성 승모판장애</option>
    <option value="I35">비류마티스성 대동맥판장애</option>
    <option value="I36">비류마티스성 삼첨판장애</option>
    <option value="I37">폐동맥판장애</option>
    <option value="I38">상세불명 판막의 심내막염</option>
    <option value="I39">달리 분류된 질환에서의 심내막염 및 심장판막장애</option>
    <option value="I40">급성 심근염</option>
    <option value="I41">달리 분류된 질환에서의 심근염</option>
    <option value="I42">심근병증</option>
    <option value="I43">달리 분류된 질환에서의 심근병증</option>
    <option value="I44">방실차단 및 좌각차단</option>
    <option value="I45">기타 전도장애</option>
    <option value="I46">심장정지</option>
    <option value="I47">발작성 빈맥</option>
    <option value="I48">심방세동 및 조동</option>
    <option value="I49">기타 심장부정맥</option>
    <option value="I50">심부전</option>
    <option value="I51">심장병의 불명확한 기록 및 합병증</option>
    <option value="I52">달리 분류된 질환에서의 기타 심장장애</option>
    <option value="I60">지주막하출혈</option>
    <option value="I61">뇌내출혈</option>
    <option value="I62">기타 비외상성 두개내출혈</option>
    <option value="I63">뇌경색증</option>
    <option value="I64">출혈 또는 경색증으로 명시되지 않은 뇌졸중</option>
    <option value="I65">뇌경색증을 유발하지 않은 뇌전동맥의 폐쇄 및 협착</option>
    <option value="I66">뇌경색증을 유발하지 않은 대뇌동맥의 폐쇄 및 협착</option>
    <option value="I67">기타 뇌혈관질환</option>
    <option value="I68">달리 분류된 질환에서의 뇌혈관장애</option>
    <option value="I69">뇌혈관질환의 후유증</option>
    <option value="I70">죽상경화증</option>
    <option value="I71">대동맥동맥류 및 박리</option>
    <option value="I72">기타 동맥류 및 박리</option>
    <option value="I73">기타 말초혈관질환</option>
    <option value="I74">동맥색전증 및 혈전증</option>
    <option value="I77">동맥 및 세동맥의 기타 장애</option>
    <option value="I78">모세혈관의 질환</option>
    <option value="I79">달리 분류된 질환에서의 동맥, 세동맥 및 모세혈관의 장애</option>
    <option value="I80">정맥염 및 혈전정맥염</option>
    <option value="I81">문맥혈전증</option>
    <option value="I82">기타 정맥의 색전증 및 혈전증</option>
    <option value="I83">하지의 정맥류</option>
    <option value="I85">식도정맥류</option>
    <option value="I86">기타 부위의 정맥류</option>
    <option value="I87">정맥의 기타 장애</option>
    <option value="I88">비특이성 림프절염</option>
    <option value="I89">림프관 및 림프절의 기타 비감염성 장애</option>
    <option value="I95">저혈압</option>
    <option value="I97">달리 분류되지 않은 순환계통의 처치후 장애</option>
    <option value="I98">달리 분류된 질환에서의 순환계통의 기타 장애</option>
    <option value="I99">순환계통의 기타 및 상세불명의 장애</option>
    
     <option value="J00">급성 비인두염 (감기)</option>
    <option value="J01">급성 부비동염</option>
    <option value="J02">급성 인두염</option>
    <option value="J03">급성 편도염</option>
    <option value="J04">급성 후두염 및 기관염</option>
    <option value="J05">급성 폐색성 후두염 (크룹) 및 후두개염</option>
    <option value="J06">다발성 및 상세불명 부위의 급성 상기도감염</option>
    <option value="J09">확인된 동물매개 또는 범유행 인플루엔자바이러스에 의한 인플루엔자</option>
    <option value="J10">확인된 계절성 인플루엔자바이러스에 의한 인플루엔자</option>
    <option value="J11">바이러스가 확인되지 않은 인플루엔자</option>
    <option value="J12">달리 분류되지 않은 바이러스폐렴</option>
    <option value="J13">폐렴연쇄구균에 의한 폐렴</option>
    <option value="J14">인플루엔자균에 의한 폐렴</option>
    <option value="J15">달리 분류되지 않은 세균성 폐렴</option>
    <option value="J16">달리 분류되지 않은 기타 감염성 병원체에 의한 폐렴</option>
    <option value="J17">달리 분류된 질환에서의 폐렴</option>
    <option value="J18">상세불명 병원체의 폐렴</option>
    <option value="J20">급성 기관지염</option>
    <option value="J21">급성 세기관지염</option>
    <option value="J22">상세불명의 급성 하기도감염</option>
    <option value="J30">혈관운동성 및 앨러지성 비염</option>
    <option value="J31">만성 비염, 비인두염 및 인두염</option>
    <option value="J32">만성 부비동염</option>
    <option value="J33">코폴립</option>
    <option value="J34">코 및 비동의 기타 장애</option>
    <option value="J35">편도 및 아데노이드의 만성 질환</option>
    <option value="J36">편도주위농양</option>
    <option value="J37">만성 후두염 및 후두기관염</option>
    <option value="J38">달리 분류되지 않은 성대 및 후두의 질환</option>
    <option value="J39">상기도의 기타 질환</option>
    <option value="J40">급성인지 만성인지 명시되지 않은 기관지염</option>
    <option value="J41">단순성 및 점액화농성 만성 기관지염</option>
    <option value="J42">상세불명의 만성 기관지염</option>
    <option value="J43">폐기종</option>
    <option value="J44">기타 만성 폐색성 폐질환</option>
    <option value="J45">천식</option>
    <option value="J46">천식지속상태</option>
    <option value="J47">기관지확장증</option>
    <option value="J60">탄광부진폐증</option>
    <option value="J61">석면 및 기타 광섬유에 의한 진폐증</option>
    <option value="J62">실리카를 함유한 먼지에 의한 진폐증</option>
    <option value="J63">기타 무기물먼지에 의한 진폐증</option>
    <option value="J64">상세불명의 진폐증</option>
    <option value="J65">결핵과 연관된 진폐증</option>
    <option value="J66">특정 유기물먼지에 의한 기도질환</option>
    <option value="J67">유기물먼지에 의한 과민성 폐렴</option>
    <option value="J68">화학물질, 가스, 훈증기 및 물김의 흡입에 의한 호흡기병태</option>
    <option value="J69">고체 및 액체에 의한 폐렴</option>
    <option value="J70">기타 외부요인에 의한 호흡기병태</option>
    <option value="J80">성인호흡곤란증후군</option>
    <option value="J81">폐부종</option>
    <option value="J82">달리 분류되지 않은 폐호산구증가</option>
    <option value="J84">기타 간질성 폐질환</option>
    <option value="J85">폐 및 종격의 농양</option>
    <option value="J86">농흉</option>
    <option value="J90">달리 분류되지 않은 흉막삼출액</option>
    <option value="J91">달리 분류된 병태에서의 흉막삼출액</option>
    <option value="J92">흉막판</option>
    <option value="J93">기흉</option>
    <option value="J94">기타 흉막의 병태</option>
    <option value="J95">달리 분류되지 않은 처치후 호흡장애</option>
    <option value="J96">달리 분류되지 않은 호흡부전</option>
    <option value="J98">기타 호흡장애</option>
    <option value="J99">달리 분류된 질환에서의 호흡장애</option>
    
    <option value="K00">치아의 발육 및 맹출 장애</option>
    <option value="K01">매몰치 및 매복치</option>
    <option value="K02">치아우식</option>
    <option value="K03">치아경조직의 기타 질환</option>
    <option value="K04">치수 및 근단주위조직의 질환</option>
    <option value="K05">치은염 및 치주질환</option>
    <option value="K06">잇몸 및 무치성 치조융기의 기타 장애</option>
    <option value="K07">치아얼굴이상[부정교합포함]</option>
    <option value="K08">치아 및 지지구조의 기타 장애</option>
    <option value="K09">달리 분류되지 않은 구강영역의 낭</option>
    <option value="K10">턱의 기타 질환</option>
    <option value="K11">침샘의 질환</option>
    <option value="K12">구내염 및 관련 병변</option>
    <option value="K13">입술 및 구강점막의 기타 질환</option>
    <option value="K14">혀의 질환</option>
    <option value="K20">식도염</option>
    <option value="K21">위-식도역류병</option>
    <option value="K22">식도의 기타 질환</option>
    <option value="K23">달리 분류된 질환에서의 식도의 장애</option>
    <option value="K25">위궤양</option>
    <option value="K26">십이지장궤양</option>
    <option value="K27">상세불명 부위의 소화성 궤양</option>
    <option value="K28">위공장궤양</option>
    <option value="K29">위염 및 십이지장염</option>
    <option value="K30">기능성 소화불량</option>
    <option value="K31">위 및 십이지장의 기타 질환</option>
    <option value="K35">급성 충수염</option>
    <option value="K36">기타 충수염</option>
    <option value="K37">상세불명의 충수염</option>
    <option value="K38">충수의 기타 질환</option>
    <option value="K40">사타구니탈장</option>
    <option value="K41">대퇴탈장</option>
    <option value="K42">배꼽탈장</option>
    <option value="K43">복벽탈장</option>
    <option value="K44">횡격막탈장</option>
    <option value="K45">기타 복벽탈장</option>
    <option value="K46">상세불명의 복벽탈장</option>
    <option value="K50">크론병[국소성 장염]</option>
    <option value="K51">궤양성 대장염</option>
    <option value="K52">기타 비감염성 위장염 및 결장염</option>
    <option value="K55">장의 혈관장애</option>
    <option value="K56">탈장이 없는 마비성 장폐색증 및 장폐색</option>
    <option value="K57">장의 게실병</option>
    <option value="K58">과민대장증후군</option>
    <option value="K59">기타 기능성 장장애</option>
    <option value="K60">항문 및 직장부의 열창 및 누공</option>
    <option value="K61">항문 및 직장부의 농양</option>
    <option value="K62">항문 및 직장의 기타 질환</option>
    <option value="K63">장의 기타 질환</option>
    <option value="K64">치핵 및 항문주위정맥혈전증</option>
    <option value="K65">복막염</option>
    <option value="K66">복막의 기타 장애</option>
    <option value="K67">달리 분류된 감염성 질환에서의 복막의 장애</option>
    <option value="K70">알콜성 간질환</option>
    <option value="K71">독성간질환</option>
    <option value="K72">달리 분류되지 않은 간부전</option>
    <option value="K73">달리 분류되지 않은 만성 간염</option>
    <option value="K74">간의 섬유증 및 경변증</option>
    <option value="K75">기타 염증성 간질환</option>
    <option value="K76">간의 기타 질환</option>
    <option value="K77">달리 분류된 질환에서의 간장애</option>
    <option value="K80">담석증</option>
    <option value="K81">담낭염</option>
    <option value="K82">담낭의 기타 질환</option>
    <option value="K83">담도의 기타 질환</option>
    <option value="K85">급성 췌장염</option>
    <option value="K86">췌장의 기타 질환</option>
    <option value="K87">달리 분류된 질환에서의 담낭, 담도 및 췌장의 장애</option>
    <option value="K90">장흡수장애</option>
    <option value="K91">달리 분류되지 않은 소화계통의 처치후 장애</option>
    <option value="K92">소화계통의 기타 질환</option>
    <option value="K93">달리 분류된 질환에서의 기타 소화기관장애</option>
    
     <option value="L00">포도구균성 화상피부증후군</option>
    <option value="L01">농가진</option>
    <option value="L02">피부의 농양, 종기 및 큰종기</option>
    <option value="L03">연조직염</option>
    <option value="L04">급성 림프절염</option>
    <option value="L05">모소낭</option>
    <option value="L08">피부 및 피하조직의 기타 국소감염</option>
    <option value="L10">천포창</option>
    <option value="L11">기타 극세포분리장애</option>
    <option value="L12">유사천포창</option>
    <option value="L13">기타 수포성 장애</option>
    <option value="L14">달리 분류된 질환에서의 수포성 장애</option>
    <option value="L20">아토피성 피부염</option>
    <option value="L21">지루피부염</option>
    <option value="L22">기저귀[냅킨]피부염</option>
    <option value="L23">앨러지성 접촉피부염</option>
    <option value="L24">자극물접촉피부염</option>
    <option value="L25">상세불명의 접촉피부염</option>
    <option value="L26">탈락피부염</option>
    <option value="L27">내부로 섭취된 물질에 의한 피부염</option>
    <option value="L28">만성 단순태선 및 가려움발진</option>
    <option value="L29">가려움</option>
    <option value="L30">기타 피부염</option>
    <option value="L40">건선</option>
    <option value="L41">유사건선</option>
    <option value="L42">장미색잔비늘증</option>
    <option value="L43">편평태선</option>
    <option value="L44">기타 구진비늘장애</option>
    <option value="L45">달리 분류된 질환에서의 구진비늘장애</option>
    <option value="L50">두드러기</option>
    <option value="L51">다형홍반</option>
    <option value="L52">결절홍반</option>
    <option value="L53">기타 홍반성 병태</option>
    <option value="L54">달리 분류된 질환에서의 홍반</option>
    <option value="L55">일광화상</option>
    <option value="L56">자외선에 의한 기타 급성 피부변화</option>
    <option value="L57">비이온화방사선 만성 노출에 의한 피부변화</option>
    <option value="L58">방사선피부염</option>
    <option value="L59">방사선에 관련된 피부 및 피하조직의 기타 장애</option>
    <option value="L60">손발톱장애</option>
    <option value="L62">달리 분류된 질환에서의 손발톱장애</option>
    <option value="L63">원형 탈모증</option>
    <option value="L64">안드로젠탈모증</option>
    <option value="L65">기타 비흉터성 모발손실</option>
    <option value="L66">흉터탈모증[흉터성 모발손실]</option>
    <option value="L67">모발색 및 모발줄기 이상</option>
    <option value="L68">털과다증</option>
    <option value="L70">여드름</option>
    <option value="L71">주사</option>
    <option value="L72">피부 및 피하조직의 모낭낭</option>
    <option value="L73">기타 모낭장애</option>
    <option value="L74">에크린땀샘장애</option>
    <option value="L75">아포크린땀샘장애</option>
    <option value="L80">백반증</option>
    <option value="L81">색소침착의 기타 장애</option>
    <option value="L82">지루각화증</option>
    <option value="L83">흑색극세포증</option>
    <option value="L84">티눈 및 굳은살</option>
    <option value="L85">기타 표피의 비후</option>
    <option value="L86">달리 분류된 질환에서의 각피증</option>
    <option value="L87">표피경유제거장애</option>
    <option value="L88">괴저성 농피증</option>
    <option value="L89">욕창궤양 및 압박부위</option>
    <option value="L90">피부의 위축장애</option>
    <option value="L91">피부의 비대성 장애</option>
    <option value="L92">피부 및 피하조직의 육아종성 장애</option>
    <option value="L93">홍반루푸스</option>
    <option value="L94">기타 국소적 결합조직장애</option>
    <option value="L95">달리 분류되지 않은 피부에 한정된 혈관염</option>
    <option value="L97">달리 분류되지 않은 다리의 궤양</option>
    <option value="L98">달리 분류되지 않은 피부 및 피하조직의 기타 장애</option>
    <option value="L99">달리 분류된 질환에서의 피부 및 피하조직의 기타 장애</option>
    
     <option value="M00">화농성 관절염</option>
    <option value="M01">달리 분류된 감염성 및 기생충성 질환에서의 관절의 직접감염</option>
    <option value="M02">반응성 관절병증</option>
    <option value="M03">달리 분류된 질환에서의 감염후 및 반응성 관절병증</option>
    <option value="M05">혈청검사양성 류마티스관절염</option>
    <option value="M06">기타 류마티스관절염</option>
    <option value="M07">건선성 및 장병성 관절병증</option>
    <option value="M08">연소성 관절염</option>
    <option value="M09">달리 분류된 질환에서의 연소성 관절염</option>
    <option value="M10">통풍</option>
    <option value="M11">기타 결정 관절병증</option>
    <option value="M12">기타 특정 관절병증</option>
    <option value="M13">기타 관절염</option>
    <option value="M14">달리 분류된 기타 질환에서의 관절병증</option>
    <option value="M15">다발관절증</option>
    <option value="M16">고관절증</option>
    <option value="M17">무릎관절증</option>
    <option value="M18">제1수근중수관절의 관절증</option>
    <option value="M19">기타 관절증</option>
    <option value="M20">손가락 및 발가락의 후천변형</option>
    <option value="M21">사지의 기타 후천변형</option>
    <option value="M22">무릎뼈의 장애</option>
    <option value="M23">무릎의 내부장애</option>
    <option value="M24">기타 특정 관절장애</option>
    <option value="M25">달리 분류되지 않은 기타 관절장애</option>
    <option value="M30">결절성 다발동맥염 및 관련 병태</option>
    <option value="M31">기타 괴사성 혈관병증</option>
    <option value="M32">전신홍반루푸스</option>
    <option value="M33">피부다발근염</option>
    <option value="M34">전신경화증</option>
    <option value="M35">결합조직의 기타 전신침범</option>
    <option value="M36">달리 분류된 질환에서의 결합조직의 전신장애</option>
    <option value="M40">척주후만증 및 척주전만증</option>
    <option value="M41">척주측만증</option>
    <option value="M42">척추골연골증</option>
    <option value="M43">기타 변형성 등병증</option>
    <option value="M45">강직척추염</option>
    <option value="M46">기타 염증성 척추병증</option>
    <option value="M47">척추증</option>
    <option value="M48">기타 척추병증</option>
    <option value="M49">달리 분류된 질환에서의 척추병증</option>
    <option value="M50">경추간판장애</option>
    <option value="M51">기타 추간판장애</option>
    <option value="M53">달리 분류되지 않은 기타 등병증</option>
    <option value="M54">등통증</option>
    <option value="M60">근염</option>
    <option value="M61">근육의 석회화 및 골화</option>
    <option value="M62">근육의 기타 장애</option>
    <option value="M63">달리 분류된 질환에서의 근육장애</option>
    <option value="M65">윤활막염 및 힘줄윤활막염</option>
    <option value="M66">윤활막 및 힘줄의 자연파열</option>
    <option value="M67">윤활막 및 힘줄의 기타 장애</option>
    <option value="M68">달리 분류된 질환에서의 윤활막 및 힘줄의 장애</option>
    <option value="M70">사용, 과용 및 압박에 관련된 연조직장애</option>
    <option value="M71">기타 윤활낭병증</option>
    <option value="M72">섬유모세포장애</option>
    <option value="M73">달리 분류된 질환에서의 연조직장애</option>
    <option value="M75">어깨병변</option>
    <option value="M76">발을 제외한 다리의 골부착부병증</option>
    <option value="M77">기타 골부착부병증</option>
    <option value="M79">달리 분류되지 않은 기타 연조직장애</option>
    <option value="M80">병적 골절을 동반한 골다공증</option>
    <option value="M81">병적 골절이 없는 골다공증</option>
    <option value="M82">달리 분류된 질환에서의 골다공증</option>
    <option value="M83">성인골연화증</option>
    <option value="M84">골연속성의 장애</option>
    <option value="M85">골밀도 및 구조의 기타 장애</option>
    <option value="M86">골수염</option>
    <option value="M87">골괴사</option>
    <option value="M88">뼈의 파젯병 (변형성 골염)</option>
    <option value="M89">뼈의 기타 장애</option>
    <option value="M90">달리 분류된 질환에서의 골병증</option>
    <option value="M91">고관절 및 골반의 연소성 골연골증</option>
    <option value="M92">기타 연소성 골연골증</option>
    <option value="M93">기타 골연골병증</option>
    <option value="M94">연골의 기타 장애</option>
    <option value="M95">근골격계통 및 결합조직의 기타 후천성 변형</option>
    <option value="M96">달리 분류되지 않은 처치후 근골격장애</option>
    <option value="M99">달리 분류되지 않은 생체역학적 병변</option>
    
     <option value="N00">급성 신염증후군</option>
    <option value="N01">급속 진행성 신염증후군</option>
    <option value="N02">재발성 및 지속성 혈뇨</option>
    <option value="N03">만성 신염증후군</option>
    <option value="N04">신증후군</option>
    <option value="N05">상세불명의 신염증후군</option>
    <option value="N06">명시된 형태학적 병변을 동반한 고립된 단백뇨</option>
    <option value="N07">달리 분류되지 않은 유전성 신장병증</option>
    <option value="N08">달리 분류된 질환에서의 사구체장애</option>
    <option value="N10">급성 세뇨관-간질신장염</option>
    <option value="N11">만성 세뇨관-간질신장염</option>
    <option value="N12">급성 또는 만성으로 명시되지 않은 세뇨관-간질신장염</option>
    <option value="N13">폐색성 및 역류성 요로병증</option>
    <option value="N14">약물 및 중금속 유발 세뇨관-간질 및 세뇨관 병태</option>
    <option value="N15">기타 신세뇨관-간질질환</option>
    <option value="N16">달리 분류된 질환에서의 신세뇨관-간질장애</option>
    <option value="N17">급성 신부전</option>
    <option value="N18">만성 신장병</option>
    <option value="N19">상세불명의 신부전</option>
    <option value="N20">신장 및 요관의 결석</option>
    <option value="N21">하부요로의 결석</option>
    <option value="N22">달리 분류된 질환에서의 요로의 결석</option>
    <option value="N23">상세불명의 신장 급통증</option>
    <option value="N25">세뇨관기능손상으로 인한 장애</option>
    <option value="N26">상세불명의 신장위축</option>
    <option value="N27">원인불명의 작은 신장</option>
    <option value="N28">달리 분류되지 않은 신장 및 요관의 기타 장애</option>
    <option value="N29">달리 분류된 질환에서의 신장 및 요관의 기타 장애</option>
    <option value="N30">방광염</option>
    <option value="N31">달리 분류되지 않은 방광의 신경근육기능장애</option>
    <option value="N32">방광의 기타 장애</option>
    <option value="N33">달리 분류된 질환에서의 방광장애</option>
    <option value="N34">요도염 및 요도증후군</option>
    <option value="N35">요도협착</option>
    <option value="N36">요도의 기타 장애</option>
    <option value="N37">달리 분류된 질환에서의 요도장애</option>
    <option value="N39">비뇨계통의 기타 장애</option>
    <option value="N40">전립선증식증</option>
    <option value="N41">전립선의 염증성 질환</option>
    <option value="N42">전립선의 기타 장애</option>
    <option value="N43">음낭수종 및 정액류</option>
    <option value="N44">고환의 염전</option>
    <option value="N45">고환염 및 부고환염</option>
    <option value="N46">남성불임</option>
    <option value="N47">과잉포피, 포경 및 감돈포경</option>
    <option value="N48">음경의 기타 장애</option>
    <option value="N49">달리 분류되지 않은 남성생식기관의 염증성 장애</option>
    <option value="N50">남성생식기관의 기타 장애</option>
    <option value="N51">달리 분류된 질환에서의 남성생식기관의 장애</option>
    <option value="N60">양성 유방형성이상</option>
    <option value="N61">유방의 염증성 장애</option>
    <option value="N62">유방의 비대</option>
    <option value="N63">유방의 상세불명의 덩이</option>
    <option value="N64">유방의 기타 장애</option>
    <option value="N70">난관염 및 난소염</option>
    <option value="N71">자궁경부를 제외한 자궁의 염증성 질환</option>
    <option value="N72">자궁경부의 염증성 질환</option>
    <option value="N73">기타 여성골반염증질환</option>
    <option value="N74">달리 분류된 질환에서의 여성골반염증장애</option>
    <option value="N75">바르톨린선의 질환</option>
    <option value="N76">질 및 외음부의 기타 염증</option>
    <option value="N77">달리 분류된 질환에서의 외음질의 궤양 및 염증</option>
    <option value="N80">자궁내막증</option>
    <option value="N81">여성생식기탈출</option>
    <option value="N82">여성생식관을 침범한 누공</option>
    <option value="N83">난소, 난관 및 넓은인대의 비염증성 장애</option>
    <option value="N84">여성생식관의 폴립</option>
    <option value="N85">자궁경부를 제외한 자궁의 기타 비염증성 장애</option>
    <option value="N86">자궁경부의 미란 및 외반</option>
    <option value="N87">자궁경부의 이형성</option>
    <option value="N88">자궁경부의 기타 비염증성 장애</option>
    <option value="N89">질의 기타 비염증성 장애</option>
    <option value="N90">외음부 및 회음부의 기타 비염증성 장애</option>
    <option value="N91">무월경, 소량 및 희발 월경</option>
    <option value="N92">과다, 빈발 및 불규칙 월경</option>
    <option value="N93">기타 이상 자궁 및 질 출혈</option>
    <option value="N94">여성생식기관 및 월경주기와 관련된 통증 및 기타 병태</option>
    <option value="N95">폐경 및 기타 폐경전후 장애</option>
    <option value="N96">습관적 유산자</option>
    <option value="N97">여성불임</option>
    <option value="N98">인공수정과 관련된 합병증</option>
    <option value="N99">달리 분류되지 않은 비뇨생식계통의 처치후 장애</option>
    
      <option value="O00">자궁외임신</option>
    <option value="O01">포상기태</option>
    <option value="O02">기타 비정상적 수태부산물</option>
    <option value="O03">자연유산</option>
    <option value="O04">의학적 유산</option>
    <option value="O05">기타 유산</option>
    <option value="O06">상세불명의 유산</option>
    <option value="O07">시도된 유산의 실패</option>
    <option value="O08">유산, 자궁외임신 및 기태임신에 따른 합병증</option>
    <option value="O10">임신, 출산 및 산후기에 합병된 전에 있던 고혈압</option>
    <option value="O11">만성 고혈압에 겹친 전자간</option>
    <option value="O12">고혈압을 동반하지 않은 임신성[임신-유발] 부종 및 단백뇨</option>
    <option value="O13">임신성[임신-유발]고혈압</option>
    <option value="O14">전자간</option>
    <option value="O15">자간</option>
    <option value="O16">상세불명의 산모고혈압</option>
    <option value="O20">초기임신중 출혈</option>
    <option value="O21">임신중 과다구토</option>
    <option value="O22">임신중 정맥합병증 및 치핵</option>
    <option value="O23">임신중 비뇨생식관의 감염</option>
    <option value="O24">임신중 당뇨병</option>
    <option value="O25">임신중 영양실조</option>
    <option value="O26">주로 임신에 관련된 기타 병태의 산모관리</option>
    <option value="O28">산모의 출산전 선별검사의 이상소견</option>
    <option value="O29">임신중 마취의 합병증</option>
    <option value="O30">다태임신</option>
    <option value="O31">다태임신에 특이한 합병증</option>
    <option value="O32">태아의 알려진 또는 의심되는 이상태위에 대한 산모관리</option>
    <option value="O33">알려진 또는 의심되는 불균형에 대한 산모관리</option>
    <option value="O34">골반기관의 알려진 또는 의심되는 이상에 대한 산모관리</option>
    <option value="O35">알려진 또는 의심되는 태아 이상 및 손상에 대한 산모관리</option>
    <option value="O36">기타 알려진 또는 의심되는 태아문제에 대한 산모관리</option>
    <option value="O40">양수과다증</option>
    <option value="O41">양수 및 양막의 기타 장애</option>
    <option value="O42">양막의 조기파열</option>
    <option value="O43">태반장애</option>
    <option value="O44">전치태반</option>
    <option value="O45">태반의 조기분리[태반조기박리]</option>
    <option value="O46">달리 분류되지 않은 분만전 출혈</option>
    <option value="O47">가진통</option>
    <option value="O48">지연임신</option>
    <option value="O60">조기진통 및 분만</option>
    <option value="O61">유도분만의 실패</option>
    <option value="O62">분만힘의 이상</option>
    <option value="O63">지연진통</option>
    <option value="O64">태아의 이상태위로 인한 난산</option>
    <option value="O65">산모골반이상으로 인한 난산</option>
    <option value="O66">기타 난산</option>
    <option value="O67">달리 분류되지 않은 분만중 출혈이 합병된 진통 및 분만</option>
    <option value="O68">태아스트레스[절박]가 합병된 진통 및 분만</option>
    <option value="O69">탯줄합병증이 합병된 진통 및 분만</option>
    <option value="O70">분만중 회음열상</option>
    <option value="O71">기타 산과적 외상</option>
    <option value="O72">분만후 출혈</option>
    <option value="O73">출혈이 없는 잔류 태반 및 양막</option>
    <option value="O74">진통 및 분만중 마취의 합병증</option>
    <option value="O75">달리 분류되지 않은 진통 및 분만의 기타 합병증</option>
    <option value="O80">단일자연분만</option>
    <option value="O81">집게 및 진공흡착기에 의한 단일분만</option>
    <option value="O82">제왕절개에 의한 단일분만</option>
    <option value="O83">기타 보조단일분만</option>
    <option value="O84">다태분만</option>
    <option value="O85">산후기 패혈증</option>
    <option value="O86">기타 산후기감염</option>
    <option value="O87">산후기중 정맥합병증 및 치핵</option>
    <option value="O88">산과적 색전증</option>
    <option value="O89">산후기중 마취의 합병증</option>
    <option value="O90">달리 분류되지 않은 산후기의 합병증</option>
    <option value="O91">출산과 관련된 유방의 감염</option>
    <option value="O92">출산과 관련된 유방 및 수유의 기타 장애</option>
    <option value="O94">임신, 출산 및 산후기 합병증의 후유증</option>
    <option value="O95">상세불명의 원인에 의한 산과적 사망</option>
    <option value="O96">분만후 42일 초과 1년 이내에 일어난 모든 산과적 원인에 의한 사망</option>
    <option value="O97">산과적 원인의 후유증에 의한 사망</option>
    <option value="O98">달리 분류될 수 있지만 임신, 출산 및 산후기에 합병된 산모의 감염성 및 기생충성 질환</option>
    <option value="O99">달리 분류될 수 있지만 임신, 출산 및 산후기에 합병된 기타</option>
    
     <option value="P00">현재 임신과는 관계 없을 것 같은 산모병태에 의해 영향받은 태아 및 신생아</option>
    <option value="P01">임신의 산모합병증에 의해 영향을 받은 태아 및 신생아</option>
    <option value="P02">태반, 탯줄 및 태아막의 합병증에 의해 영향을 받은 태아 및 신생아</option>
    <option value="P03">진통 및 분만의 기타 합병증에 의해 영향을 받은 태아 및 신생아</option>
    <option value="P04">태반 또는 모유를 통해 전달된 해로운 작용에 의해 영향을 받은 태아 및 신생아</option>
    <option value="P05">태아성장지연 및 태아영양실조</option>
    <option value="P07">달리 분류되지 않은 단기임신 및 저체중출산에 관련된 장애</option>
    <option value="P08">장기임신 및 고체중출산에 관련된 장애</option>
    <option value="P10">출산손상으로 인한 두개내 열상 및 출혈</option>
    <option value="P11">중추신경계통에 대한 기타 출산손상</option>
    <option value="P12">두피의 출산손상</option>
    <option value="P13">골격의 출산손상</option>
    <option value="P14">말초 신경계통의 출산손상</option>
    <option value="P15">기타 출산손상</option>
    <option value="P20">자궁내저산소증</option>
    <option value="P21">출산질식</option>
    <option value="P22">신생아의 호흡곤란</option>
    <option value="P23">선천폐렴</option>
    <option value="P24">신생아흡인증후군</option>
    <option value="P25">출생전후기에 기원한 간질성 폐기종 및 관련 병태</option>
    <option value="P26">출생전후기에 기원한 폐출혈</option>
    <option value="P27">출생전후기에 기원한 만성 호흡기질환</option>
    <option value="P28">출생전후기에 기원한 기타 호흡기병태</option>
    <option value="P29">출생전후기에 기원한 심혈관장애</option>
    <option value="P35">선천성 바이러스질환</option>
    <option value="P36">신생아의 세균패혈증</option>
    <option value="P37">기타 선천성 감염 및 기생충질환</option>
    <option value="P38">경도의 출혈을 동반하거나 동반하지 않은 신생아배꼽염</option>
    <option value="P39">출생전후기에 특이한 기타 감염</option>
    <option value="P50">태아실혈</option>
    <option value="P51">신생아의 탯줄출혈</option>
    <option value="P52">태아 및 신생아의 두개내 비외상성 출혈</option>
    <option value="P53">태아 및 신생아의 출혈성 질환</option>
    <option value="P54">기타 신생아출혈</option>
    <option value="P55">태아 및 신생아의 용혈질환</option>
    <option value="P56">용혈질환으로 인한 태아수종</option>
    <option value="P57">핵황달</option>
    <option value="P58">기타 과다용혈로 인한 신생아황달</option>
    <option value="P59">기타 및 상세불명의 원인으로 인한 신생아황달</option>
    <option value="P60">태아 및 신생아의 파종성 혈관내응고</option>
    <option value="P61">기타 출생전후기 혈액학적 장애</option>
    <option value="P70">태아 및 신생아에 특이한 일과성 탄수화물대사장애</option>
    <option value="P71">일과성 신생아 칼슘 및 마그네슘 대사장애</option>
    <option value="P72">기타 일과성 신생아내분비장애</option>
    <option value="P74">기타 일과성 신생아 전해질 및 대사 장애</option>
    <option value="P75">낭성 섬유증에서의 태변장폐색</option>
    <option value="P76">신생아의 기타 장폐색</option>
    <option value="P77">태아 및 신생아의 괴사성 장결장염</option>
    <option value="P78">기타 출생전후기 소화계통장애</option>
    <option value="P80">신생아의 저체온증</option>
    <option value="P81">신생아 체온조절의 기타 장애</option>
    <option value="P83">태아 및 신생아에 특이한 피부의 기타 병태</option>
    <option value="P90">신생아의 경련</option>
    <option value="P91">신생아 대뇌상태의 기타 장애</option>
    <option value="P92">신생아의 수유문제</option>
    <option value="P93">태아 및 신생아에게 투여한 약물의 반응 및 중독</option>
    <option value="P94">신생아의 근긴장도의 장애</option>
    <option value="P95">상세불명 원인의 태아사망</option>
    <option value="P96">출생전후기에 기원한 기타</option>
    
    <option value="Q00">무뇌증 및 유사 기형</option>
    <option value="Q01">뇌류(腦瘤)</option>
    <option value="Q02">소두증</option>
    <option value="Q03">선천수두증</option>
    <option value="Q04">뇌의 기타 선천기형</option>
    <option value="Q05">이분척추</option>
    <option value="Q06">척수의 기타 선천기형</option>
    <option value="Q07">신경계통의 기타 선천기형</option>
    <option value="Q10">눈꺼풀, 눈물기관 및 안와의 선천기형</option>
    <option value="Q11">무안구증, 소안구증 및 대안구증</option>
    <option value="Q12">선천성 수정체기형</option>
    <option value="Q13">전안부의 선천기형</option>
    <option value="Q14">후안부의 선천기형</option>
    <option value="Q15">눈의 기타 선천기형</option>
    <option value="Q16">청력장애를 유발하는 귀의 선천기형</option>
    <option value="Q17">귀의 기타 선천기형</option>
    <option value="Q18">얼굴 및 목의 기타 선천기형</option>
    <option value="Q20">심장 방실 및 연결의 선천기형</option>
    <option value="Q21">심장중격의 선천기형</option>
    <option value="Q22">폐동맥판 및 삼첨판의 선천기형</option>
    <option value="Q23">대동맥판 및 승모판의 선천기형</option>
    <option value="Q24">심장의 기타 선천기형</option>
    <option value="Q25">대동맥혈관의 선천기형</option>
    <option value="Q26">대정맥혈관의 선천기형</option>
    <option value="Q27">말초혈관계통의 기타 선천기형</option>
    <option value="Q28">순환계통의 기타 선천기형</option>
    <option value="Q30">코의 선천기형</option>
    <option value="Q31">후두의 선천기형</option>
    <option value="Q32">기관 및 기관지의 선천기형</option>
    <option value="Q33">폐의 선천기형</option>
    <option value="Q34">호흡계통의 기타 선천기형</option>
    <option value="Q35">구개열</option>
    <option value="Q36">구순열</option>
    <option value="Q37">구순열을 동반한 구개열</option>
    <option value="Q38">혀, 입 및 인두의 기타 선천기형</option>
    <option value="Q39">식도의 선천기형</option>
    <option value="Q40">상부소화관의 기타 선천기형</option>
    <option value="Q41">소장의 선천성 결여, 폐쇄 및 협착</option>
    <option value="Q42">대장의 선천 결여, 폐쇄 및 협착</option>
    <option value="Q43">장의 기타 선천기형</option>
    <option value="Q44">담낭, 담관 및 간의 선천기형</option>
    <option value="Q45">소화계통의 기타 선천기형</option>
    <option value="Q50">난소, 난관 및 넓은인대의 선천기형</option>
    <option value="Q51">자궁 및 자궁경부의 선천기형</option>
    <option value="Q52">여성생식기의 기타 선천기형</option>
    <option value="Q53">미하강고환</option>
    <option value="Q54">요도하열</option>
    <option value="Q55">남성생식기관의 기타 선천기형</option>
    <option value="Q56">불확정 성 및 거짓반음양증</option>
    <option value="Q60">신장무발생 및 신장의 기타 감소결손</option>
    <option value="Q61">낭성 신장병</option>
    <option value="Q62">신우의 선천성 폐색성 결손 및 요관의 선천기형</option>
    <option value="Q63">신장의 기타 선천기형</option>
    <option value="Q64">비뇨계통의 기타 선천기형</option>
    <option value="Q65">고관절의 선천변형</option>
    <option value="Q66">발의 선천변형</option>
    <option value="Q67">머리, 얼굴, 척추 및 흉부의 선천성 근골격변형</option>
    <option value="Q68">기타 선천성 근골격변형</option>
    <option value="Q69">다지증</option>
    <option value="Q70">합지증</option>
    <option value="Q71">팔의 감소결손</option>
    <option value="Q72">다리의 감소결손</option>
    <option value="Q73">상세불명 사지의 감소결손</option>
    <option value="Q74">사지의 기타 선천기형</option>
    <option value="Q75">두개골 및 안면골의 기타 선천기형</option>
    <option value="Q76">척추 및 골성 흉곽의 선천기형</option>
    <option value="Q77">관상골 및 척추의 성장결손을 동반한 골연골형성이상</option>
    <option value="Q78">기타 골연골형성이상</option>
    <option value="Q79">달리 분류되지 않은 근골격계통의 선천기형</option>
    <option value="Q80">선천비늘증</option>
    <option value="Q81">수포성 표피박리증</option>
    <option value="Q82">피부의 기타 선천기형</option>
    <option value="Q83">유방의 선천기형</option>
    <option value="Q84">외피의 기타 선천기형</option>
    <option value="Q85">달리 분류되지 않은 모반증</option>
    <option value="Q86">달리 분류되지 않은 알려진 외인으로 인한 선천기형증후군</option>
    <option value="Q87">다발계통에 영향을 주는 기타 명시된 선천기형증후군</option>
    <option value="Q89">달리 분류되지 않은 기타 선천기형</option>
    <option value="Q90">다운증후군</option>
    <option value="Q91">에드워즈증후군 및 파타우증후군</option>
    <option value="Q92">달리 분류되지 않은 보통염색체의 기타 삼염색체증 및 부분삼염색체증</option>
    <option value="Q93">달리 분류되지 않은 보통염색체의 단일염색체증 및 결손</option>
    <option value="Q95">달리 분류되지 않은 균형된 재배열 및 구조표지자</option>
    <option value="Q96">터너증후군</option>
    <option value="Q97">달리 분류되지 않은 여성표현형의 기타 성염색체이상</option>
    <option value="Q98">달리 분류되지 않은 남성표현형의 기타 성염색체이상</option>
    <option value="Q99">달리 분류되지 않은 기타 염색체이상</option>
    
    <option value="R00">심장박동의 이상</option>
    <option value="R01">심잡음 및 기타 심음</option>
    <option value="R02">달리 분류되지 않은 괴저</option>
    <option value="R03">진단명 없는 혈압수치이상</option>
    <option value="R04">기도출혈</option>
    <option value="R05">기침</option>
    <option value="R06">호흡의 이상</option>
    <option value="R07">목구멍 및 가슴의 통증</option>
    <option value="R09">순환계통 및 호흡계통의 기타 증상 및 징후</option>
    <option value="R10">복부 및 골반 통증</option>
    <option value="R11">구역 및 구토</option>
    <option value="R12">속쓰림</option>
    <option value="R13">삼킴곤란</option>
    <option value="R14">고창 및 연관된 병태</option>
    <option value="R15">대변실금</option>
    <option value="R16">달리 분류되지 않은 간비대 및 비장비대</option>
    <option value="R17">상세불명의 황달</option>
    <option value="R18">복수</option>
    <option value="R19">소화계통 및 복부의 기타 증상 및 징후</option>
    <option value="R20">피부감각의 장애</option>
    <option value="R21">발진 및 기타 비특이성 피부발진</option>
    <option value="R22">피부 및 피하조직의 국소적 부기, 종괴 및 덩이</option>
    <option value="R23">기타 피부변화</option>
    <option value="R25">이상불수의운동</option>
    <option value="R26">보행과 이동의 이상</option>
    <option value="R27">기타 협조결여</option>
    <option value="R29">신경계통 및 근골격계통의 기타 증상 및 징후</option>
    <option value="R30">배뇨와 연관된 통증</option>
    <option value="R31">상세불명의 혈뇨</option>
    <option value="R32">상세불명의 요실금</option>
    <option value="R33">소변정체</option>
    <option value="R34">무뇨 및 핍뇨</option>
    <option value="R35">다뇨</option>
    <option value="R36">요도분비물</option>
    <option value="R39">비뇨계통의 기타 증상 및 징후</option>
    <option value="R40">기면, 혼미 및 혼수</option>
    <option value="R41">인지기능 및 자각에 관련된 기타 증상 및 징후</option>
    <option value="R42">어지럼증 및 어지럼</option>
    <option value="R43">후각 및 미각 장애</option>
    <option value="R44">일반적 감각 및 지각에 관련된 기타 증상 및 징후</option>
    <option value="R45">정서상태에 관련된 증상 및 징후</option>
    <option value="R46">외양 및 행동에 관련된 증상 및 징후</option>
    <option value="R47">달리 분류되지 않은 언어장애</option>
    <option value="R48">달리 분류되지 않은 난독증 및 기타 상징적 기능이상</option>
    <option value="R49">음성장애</option>
    <option value="R50">기타 및 원인미상의 열</option>
    <option value="R51">두통</option>
    <option value="R52">달리 분류되지 않은 통증</option>
    <option value="R53">병감 및 피로</option>
    <option value="R54">노쇠</option>
    <option value="R55">실신 및 허탈</option>
    <option value="R56">달리 분류되지 않은 경련</option>
    <option value="R57">달리 분류되지 않은 쇼크</option>
    <option value="R58">달리 분류되지 않은 출혈</option>
    <option value="R59">림프절비대</option>
    <option value="R60">달리 분류되지 않은 부종</option>
    <option value="R61">다한증</option>
    <option value="R62">기대되는 정상 생리학적 발달의 결여</option>
    <option value="R63">음식 및 수액 섭취에 관계된 증상 및 징후</option>
    <option value="R64">카켁시아</option>
    <option value="R65">전신염증반응증후군</option>
    <option value="R68">기타 전신 증상 및 징후</option>
    <option value="R69">미상 및 상세불명의 병인</option>
    <option value="R70">적혈구침강속도의 상승 및 혈장점도의 이상</option>
    <option value="R71">적혈구의 이상</option>
    <option value="R72">달리 분류되지 않은 백혈구의 이상</option>
    <option value="R73">혈당치상승</option>
    <option value="R74">이상혈청효소수치</option>
    <option value="R75">인체면역결핍바이러스의 검사실 증거</option>
    <option value="R76">혈청의 기타 면역학적 이상소견</option>
    <option value="R77">혈장단백질의 기타 이상</option>
    <option value="R78">정상적으로는 혈액내에 없는 약물 및 기타 물질의 소견</option>
    <option value="R79">혈액화학의 기타 이상소견</option>
    <option value="R80">고립된 단백뇨</option>
    <option value="R81">당뇨</option>
    <option value="R82">요의 기타 이상소견</option>
    <option value="R83">뇌척수액의 이상소견</option>
    <option value="R84">호흡기관 및 흉부 검사물의 이상소견</option>
    <option value="R85">소화기관 및 복강 검사물의 이상소견</option>
    <option value="R86">남성생식기관 검사물의 이상소견</option>
    <option value="R87">여성생식기관 검사물의 이상소견</option>
    <option value="R89">기타 기관, 계통 및 조직 검사물의 이상소견</option>
    <option value="R90">중추신경계통의 진단적 영상검사의 이상소견</option>
    <option value="R91">폐의 진단적 영상검사상 이상소견</option>
    <option value="R92">유방의 진단적 영상이상소견</option>
    <option value="R93">기타 신체구조의 진단적 영상검사상 이상소견</option>
    <option value="R94">기능검사의 이상결과</option>
    <option value="R95">영아돌연사증후군</option>
    <option value="R96">원인 미상의 기타 돌연사</option>
    <option value="R98">지켜본 사람이 없었던 사망</option>
    <option value="R99">기타 불명확하고 상세불명의 사망원인</option>
    
    <option value="S00">머리의 표재성 손상</option>
        <option value="S01">머리의 열린상처</option>
        <option value="S02">두개골 및 안면골의 골절</option>
        <option value="S03">머리의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S04">뇌신경의 손상</option>
        <option value="S05">눈 및 안와의 손상</option>
        <option value="S06">두개내손상</option>
        <option value="S07">머리의 으깸손상</option>
        <option value="S08">머리 부분의 외상성 절단</option>
        <option value="S09">머리의 기타 및 상세불명의 손상</option>
     <option value="S10">목의 표재성 손상</option>
        <option value="S11">목의 열린상처</option>
        <option value="S12">목의 골절</option>
        <option value="S13">목부위의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S14">목부위의 신경 및 척수의 손상</option>
        <option value="S15">목부위의 혈관의 손상</option>
        <option value="S16">목부위의 근육 및 힘줄의 손상</option>
        <option value="S17">목의 으깸손상</option>
        <option value="S18">목부위의 외상성 절단</option>
        <option value="S19">목의 기타 및 상세불명의 손상</option>
    <option value="S20">흉부의 표재성 손상</option>
        <option value="S21">흉부의 열린상처</option>
        <option value="S22">늑골, 흉골 및 흉추의 골절</option>
        <option value="S23">흉곽의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S24">흉부부위의 신경 및 척수의 손상</option>
        <option value="S25">흉부 혈관의 손상</option>
        <option value="S26">심장의 손상</option>
        <option value="S27">기타 및 상세불명의 흉곽내기관의 손상</option>
        <option value="S28">흉부의 으깸손상 및 흉부 부분의 외상성 절단</option>
        <option value="S29">흉부의 기타 및 상세불명의 손상</option>
     <option value="S30">복부, 아래다리 및 골반의 표재성 손상</option>
        <option value="S31">복부, 아래다리 및 골반의 열린상처</option>
        <option value="S32">요추 및 골반의 골절</option>
        <option value="S33">요추 및 골반의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S34">복부, 아래다리 및 골반 부위의 신경 및 허리척수의 손상</option>
        <option value="S35">복부, 아래다리 및 골반 부위의 혈관의 손상</option>
        <option value="S36">복강내기관의 손상</option>
        <option value="S37">비뇨 및 골반 기관의 손상</option>
        <option value="S38">복부, 아래다리 및 골반의 으깸손상 및 외상성 절단</option>
        <option value="S39">복부, 아래다리 및 골반의 기타 및 상세불명의 손상</option>
    <option value="S40">어깨 및 위팔의 표재성 손상</option>
        <option value="S41">어깨 및 위팔의 열린상처</option>
        <option value="S42">어깨 및 위팔의 골절</option>
        <option value="S43">견갑대의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S44">어깨 및 위팔 부위의 신경의 손상</option>
        <option value="S45">어깨 및 위팔 부위의 혈관의 손상</option>
        <option value="S46">어깨 및 위팔 부위의 근육 및 힘줄의 손상</option>
        <option value="S47">어깨 및 위팔의 으깸손상</option>
        <option value="S48">어깨 및 위팔의 외상성 절단</option>
        <option value="S49">어깨 및 위팔의 기타 및 상세불명의 손상</option>
    <option value="S50">아래팔의 표재성 손상</option>
        <option value="S51">아래팔의 열린상처</option>
        <option value="S52">아래팔의 골절</option>
        <option value="S53">팔꿈치의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S54">아래팔 부위의 신경의 손상</option>
        <option value="S55">아래팔 부위의 혈관의 손상</option>
        <option value="S56">아래팔 부위의 근육 및 힘줄의 손상</option>
        <option value="S57">아래팔의 으깸손상</option>
        <option value="S58">아래팔의 외상성 절단</option>
        <option value="S59">아래팔의 기타 및 상세불명의 손상</option>
    <option value="S60">손목 및 손의 표재성 손상</option>
        <option value="S61">손목 및 손의 열린상처</option>
        <option value="S62">손목 및 손부위의 골절</option>
        <option value="S63">손목 및 손부위의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S64">손목 및 손 부위의 신경의 손상</option>
        <option value="S65">손목 및 손 부위의 혈관의 손상</option>
        <option value="S66">손목 및 손 부위의 근육 및 힘줄의 손상</option>
        <option value="S67">손목 및 손의 으깸손상</option>
        <option value="S68">손목 및 손의 외상성 절단</option>
        <option value="S69">손목 및 손의 기타 및 상세불명의 손상</option>
      <option value="S70">엉덩이 및 대퇴의 표재성 손상</option>
        <option value="S71">엉덩이 및 대퇴의 열린상처</option>
        <option value="S72">대퇴골의 골절</option>
        <option value="S73">고관절의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S74">엉덩이 및 대퇴 부위의 신경의 손상</option>
        <option value="S75">엉덩이 및 대퇴 부위의 혈관의 손상</option>
        <option value="S76">엉덩이 및 대퇴 부위의 근육 및 힘줄의 손상</option>
        <option value="S77">엉덩이 및 대퇴의 으깸손상</option>
        <option value="S78">엉덩이 및 대퇴의 외상성 절단</option>
        <option value="S79">엉덩이 및 대퇴의 기타 및 상세불명의 손상</option>
    <option value="S80">아래다리의 표재성 손상</option>
        <option value="S81">아래다리의 열린상처</option>
        <option value="S82">발목을 포함한 아래다리의 골절</option>
        <option value="S83">무릎의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S84">아래다리 부위의 신경의 손상</option>
        <option value="S85">아래다리 부위의 혈관의 손상</option>
        <option value="S86">아래다리 부위의 근육 및 힘줄의 손상</option>
        <option value="S87">아래다리의 으깸손상</option>
        <option value="S88">아래다리의 외상성 절단</option>
        <option value="S89">아래다리의 기타 및 상세불명의 손상</option>
    <option value="S90">발목 및 발의 표재성 손상</option>
        <option value="S91">발목 및 발의 열린상처</option>
        <option value="S92">발목을 제외한 발의 골절</option>
        <option value="S93">발목 및 발 부위의 관절 및 인대의 탈구, 염좌 및 긴장</option>
        <option value="S94">발목 및 발 부위의 신경의 손상</option>
        <option value="S95">발목 및 발 부위의 혈관의 손상</option>
        <option value="S96">발목 및 발 부위의 근육 및 힘줄의 손상</option>
        <option value="S97">발목 및 발의 으깸손상</option>
        <option value="S98">발목 및 발의 외상성 절단</option>
        <option value="S99">발목 및 발의 기타 및 상세불명의 손상</option>
        
      <option value="T00">여러 신체부위를 침범한 표재성 손상</option>
        <option value="T01">여러 신체부위를 침범한 열린상처</option>
        <option value="T02">여러 신체부위를 침범한 골절</option>
        <option value="T03">여러 신체부위를 침범한 탈구, 염좌 및 긴장</option>
        <option value="T04">여러 신체부위를 침범한 으깸손상</option>
        <option value="T05">여러 신체부위를 침범한 외상성 절단</option>
        <option value="T06">달리 분류되지 않은 여러 신체부위를 침범한 기타 손상</option>
        <option value="T07">상세불명의 다발손상</option>
     <option value="T20">머리 및 목의 화상 및 부식</option>
        <option value="T21">몸통의 화상 및 부식</option>
        <option value="T22">손목 및 손을 제외한 어깨와 팔의 화상 및 부식</option>
        <option value="T23">손목 및 손의 화상 및 부식</option>
        <option value="T24">발목 및 발을 제외한 엉덩이 및 다리의 화상 및 부식</option>
        <option value="T25">발목 및 발의 화상 및 부식</option>
        <option value="T26">눈 및 부속기에 국한된 화상 및 부식</option>
        <option value="T27">기도의 화상 및 부식</option>
        <option value="T28">기타 내부기관의 화상 및 부식</option>
        <option value="T29">여러 신체부위를 침범하는 화상 및 부식</option>
        <option value="T30">상세불명 신체부위의 화상 및 부식</option>
        <option value="T31">포함된 신체표면의 정도에 따라 분류된 화상</option>
        <option value="T32">포함된 신체표면의 정도에 따라 분류된 부식</option>
    <option value="T33">표재성 동상</option>
        <option value="T34">조직괴사를 동반한 동상</option>
        <option value="T35">여러 신체부위를 침범한 동상 및 상세불명의 동상</option>  
     <option value="T36">전신항생제에 의한 중독</option>
        <option value="T37">기타 전신 항감염제 및 항기생충제에 의한 중독</option>
        <option value="T38">달리 분류되지 않은 호르몬, 합성호르몬대치물 및 길항제에 의한 중독</option>
        <option value="T39">비아편유사진통제, 해열제 및 항류마티스제에 의한 중독</option>
        <option value="T40">마약 및 정신이상약[환각제]에 의한 중독</option>
        <option value="T41">마취제 및 각종 치료용가스에 의한 중독</option>
        <option value="T42">항뇌전증제, 진정제-수면제 및 항파킨슨제에 의한 중독</option>
        <option value="T43">달리 분류되지 않은 정신작용제에 의한 중독</option>
        <option value="T44">일차적으로 자율신경계통에 작용하는 약물에 의한 중독</option>
        <option value="T45">달리 분류되지 않은 주로 전신 및 혈액에 작용하는 제제에 의한 중독</option>
        <option value="T46">주로 심혈관계통에 영향을 주는 제제에 의한 중독</option>
        <option value="T47">주로 위장계통에 영향을 주는 제제에 의한 중독</option>
        <option value="T48">주로 평활근, 골격근 및 호흡계통에 작용하는 제제에 의한 중독</option>
        <option value="T49">주로 피부 및 점막에 영향을 주는 국소제제와 안과, 이비인후과 및 치과 약물에 의한 중독</option>
        <option value="T50">이뇨제 및 기타 상세불명의 약물, 약제 및 생물학적 물질에 의한 중독</option>
        <option value="T51">알콜의 독성효과</option>
        <option value="T52">유기용제의 독성효과</option>
        <option value="T53">지방족 및 방향족탄화수소의 할로겐유도체의 독성효과</option>
        <option value="T54">부식물질의 독성효과</option>
        <option value="T55">비누 및 세제의 독성효과</option>
        <option value="T56">금속의 독성효과</option>
        <option value="T57">기타 무기물질의 독성효과</option>
        <option value="T58">일산화탄소의 독성효과</option>
        <option value="T59">기타 가스, 연무 또는 물김의 독성효과</option>
        <option value="T60">유해생물방제제(농약)의 독성효과</option>
        <option value="T61">해산물로 섭취한 유해물질의 독성효과</option>
        <option value="T62">식품으로 섭취한 기타 유해물질의 독성효과</option>
        <option value="T63">독액성 동물과의 접촉의 독성효과</option>
        <option value="T64">아플라톡신 및 기타 진균독소 식품오염물질의 독성효과</option>
        <option value="T65">기타 및 상세불명 물질의 독성효과</option>
    <option value="T66">방사선의 상세불명의 영향</option>
        <option value="T67">열 및 빛의 영향</option>
        <option value="T68">저체온증</option>
        <option value="T69">저하된 온도의 기타 영향</option>
        <option value="T70">기압 및 수압의 영향</option>
        <option value="T71">질식</option>
        <option value="T73">기타 박탈의 영향</option>
        <option value="T74">학대증후군</option>
        <option value="T75">기타 외인의 영향</option>
        <option value="T78">달리 분류되지 않은 유해작용</option>
        <option value="T79">달리 분류되지 않은 외상의 특정 조기합병증</option>
        <option value="T80">주입, 수혈 및 치료용 주사에 따른 합병증</option>
        <option value="T81">달리 분류되지 않은 처치의 합병증</option>
        <option value="T82">심장 및 혈관 인공삽입장치, 삽입물 및 이식편의 합병증</option>
        <option value="T83">비뇨생식기 인공삽입장치, 삽입물 및 이식편의 합병증</option>
        <option value="T84">내부 정형외과적 인공삽입장치, 삽입물 및 이식편의 합병증</option>
        <option value="T85">기타 내부 인공삽입장치, 삽입물 및 이식편의 합병증</option>
        <option value="T86">이식된 기관 및 조직의 실패 및 거부</option>
        <option value="T87">재부착 및 절단에 특이한 합병증</option>
        <option value="T88">달리 분류되지 않은 외과적 및 내과적 치료의 기타 합병증</option>
        <option value="T90">머리손상의 후유증</option>
        <option value="T91">목 및 몸통 손상의 후유증</option>
        <option value="T92">팔손상의 후유증</option>
        <option value="T93">다리손상의 후유증</option>
        <option value="T94">다발성 및 상세불명의 신체부위를 침범한 손상의 후유증</option>
        <option value="T95">화상, 부식 및 동상의 후유증</option>
        <option value="T96">약물, 약제 및 생물학적 물질에 의한 중독의 후유증</option>
        <option value="T97">출처가 주로 비의약품인 물질의 독성효과의 후유증</option>
        <option value="T98">외인의 기타 및 상세불명 영향의 후유증</option>
    
    <option value="U04">중증급성호흡증후군[SARS]</option>
<option value="U06">U06의 응급사용</option>
<option value="U07">U07의 응급사용</option>
<option value="U19">중동호흡기증후군 [MERS]</option>
<option value="U50">육음병증(六淫病證)</option>
<option value="U52">태양병증(太陽病證)</option>
<option value="U53">양명병증(陽明病證)</option>
<option value="U54">소양병증(少陽病證)</option>
<option value="U55">태음병증(太陰病證)</option>
<option value="U56">소음병증(少陰病證)</option>
<option value="U57">궐음병증(厥陰病證)</option>
<option value="U60">기병증(氣病證)</option>
<option value="U61">혈병증(血病證)</option>
<option value="U62">기혈음양병증(氣血陰陽病證)</option>
<option value="U63">진액병증(津液病證)</option>
<option value="U64">간허증(肝虛證)</option>
<option value="U65">간실증(肝實證)</option>
<option value="U66">심허증(心虛證)</option>
<option value="U67">심실증(心實證)</option>
<option value="U69">폐허증(肺虛證)</option>
<option value="U70">폐실증(肺實證)</option>
<option value="U71">신병증(腎病證)</option>
<option value="U72">담병증(膽病證)</option>
<option value="U73">위병증(胃病證)</option>
<option value="U74">대장병증(大腸病證)</option>
<option value="U75">소장병증(小腸病證)</option>
<option value="U76">방광병증(膀胱病證)</option>
<option value="U77">충임포궁병증(衝任胞宮病證)</option>
<option value="U82">베타락탐항생제 내성</option>
<option value="U83">기타 항생제 내성</option>
<option value="U84">기타 항균제 내성</option>
<option value="U85">항암제 내성</option>
<option value="U95">소음인병증(少陰人病證)</option>
<option value="U96">소양인병증(少陽人病證)</option>
<option value="U97">태음인병증(太陰人病證)</option>
<option value="U98">태양인병증(太陽人病證)</option>
<option value="U99">재발한 악성 신생물</option>

    </select>
    
    <button onclick="filterData()">필터 적용</button>
    
<!-- 	<form action="/disease/list"> -->
<!-- 		<label for="sickCd">질병코드:</label> -->
<!-- 		<input type="text" id="sickCd" name="sickCd" required> -->
<!-- 		<button type="submit">확인</button> -->
<!-- 	</form> -->

	<hr>
 <c:if test="${not empty itemList}">
	<c:forEach items="${itemList}" var="item">
	
	
<c:if test="${item.age == param.ageRange && item.sex == param.gender && item.sickCd == param.sickCd}">
                <div>
                    <h3> ${item.sickNm} ${param.ageRange} ${param.gender == '남' ? '남성' : '여성'}</h3>
                    [질병 코드] ${item.sickCd} <br>
                    [질병 이름] ${item.sickNm} <br>
                    [나이] ${item.age} <br>
                    [성별] ${item.sex} <br>
                    [환자 수] ${item.ptntCnt} <br>
                </div>
            </c:if>

	</c:forEach>
	</c:if>
	
	
</body>
</html>